### ISSUE TITLE
Please, add "question" label

### ISSUE THREAD

**Issue by woodlist** [doppelgrau/ESP32-LAN8720-Core-OTA#1]
Hi!
Could you please, add WEB OTA, namely, when the bin located somewhere in Internet with version info in separate JSON. The MC should check own version with server version. If server version is greater then the own, let's firmware upgrade go on. Let's the OTA checking take place, once, at MC initialization. For OTA report, let's the MC write another JSON as report. How is the idea?

**Comment by doppelgrau** [comment]
Does not make sense for this use case, where this is generic, waiting for the real image to be flashed 8especally, since the network configuration is hard coded, with no gateway...)
